---
server:
  cluster:
    domain: cluster.starsystem.dev
    disable: 
      - traefik # Managed ourselves via Flux
      - servicelb # Replaced with kube-vip
      - local-storage # We manage this ourselves
    disable_cloud_controller: true # So kube-vip can manage LoadBalancer services