---
- name: Download FluxCD installation script
  ansible.builtin.get_url:
    url: https://fluxcd.io/install.sh
    dest: /tmp/fluxcd/install.sh
    mode: "0700" # U:RWX, G:N, O:N

- name: Run installation script
  ansible.builtin.command:
    cmd: bash /tmp/fluxcd/install.sh
  register: script_result
  changed_when: script_result.rc == 0
