---
- name: Update hostname file
  ansible.builtin.copy:
    dest: /etc/hostname
    content: |
      {{ inventory_hostname }}
    owner: root
    group: root
    mode: "0644" # U:RW, G:R, O:R

- name: Update hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '127.0.1.1'
    line: "127.0.1.1 {{ inventory_hostname }}.local {{ inventory_hostname }}"
    owner: root
    group: root
    mode: "0644" # U:RW, G:R, O:R
    state: present
