---
- name: Initialise the cluster with the master node
  hosts: master[0]

  tasks:
    - include_role:
        name: master
      vars:
        master_vars: "{{ master }}"

- name: Join additional server nodes to the cluster
  hosts: servers

  tasks:
    - include_role:
        name: server
      vars:
        server_vars:
          token: "{{ hostvars[groups['master'][0]]['master_token'] }}"
          join_ip: "{{ hostvars[groups['master'][0]]['master_ip'] }}"
          cluster: "{{ server.cluster }}"
          labels: "{{ server.labels | default('[]') }}"
          taints: "{{ server.taints | default('[]') }}"

- name: Join agents to the cluster
  hosts: agents

  tasks:
    - include_role:
        name: agent
      vars:
        agent_vars:
          token: "{{ hostvars[groups['master'][0]]['master_token'] }}"
          join_ip: "{{ hostvars[groups['master'][0]]['master_ip'] }}"
          labels: "{{ agent.labels | default('[]') }}"
          taints: "{{ agent.taints | default('[]') }}"

- name: Deploy Flux to the cluster
  hosts: master[0]
  vars_prompt:
    - name: flux_private_key_path
      prompt: GitHub SSH private key path
      private: false

    - name: flux_private_key_passphrase
      prompt: Private key passphrase

  tasks:
    - include_role:
        name: flux
      vars:
        flux_vars: "{{ flux }}"
