---
- name: Deploy all Kubernetes server nodes
  hosts: servers

  tasks:
    - include_role:
        name: server
      vars: {{ server }}

- name: Deploy agents to the Kubernetes cluster
  hosts: agents
  
  tasks:
    - include_role:
        name: agent
      vars: {{ agent }}

- name: Deploy Flux to the cluster
  hosts: servers

  tasks:
    - include_role:
        name: flux
      vars: {{ flux }}
      run_once: true