---
- name: Set a few special options for TrueNAS nodes
  hosts: truenas

  tasks:
    - name: Disable the read only file system
      ansible.builtin.command:
        cmd: /usr/local/libexec/disable-rootfs-protection
      register: script_result
      changed_when: script_result.rc == 0

- name: Configure common node options
  hosts: all

  tasks:
    - include_role:
        name: hostname

    - include_role:
        name: motd

    - name: Mount all the drives, Ansible will add to fstab if needed
      ansible.posix.mount:
        path: "{{ item.mountpoint }}"
        src: "{{ item.device }}"
        fstype: "{{ item.fs }}"
        boot: true
        state: mounted
      loop: "{{ drives }}"

    - include_role:
        name: ssh
      vars:
        ssh_vars: "{{ ssh }}"

- name: Configure specific features for Raspberry Pis
  hosts: raspberrypis

  tasks:
    - include_role:
        name: raspberrypi
      vars:
        raspberrypi_vars: "{{ raspberrypi }}"

    - include_role:
        name: pironman5
      when: model is regex('^Raspberry Pi 5')

    - include_role:
        name: argon40
      when: model is regex('^Raspberry Pi 4')

- name: Reboot all physical nodes so changes can take effect
  hosts: baremetal # By rebooting the host, VMs will also be rebooted, so we don't need to send them a reboot command. If we don't skip VMs, we end up with errors

  tasks:
    - ansible.builtin.reboot:
