---
- name: Download script
  ansible.builtin.get_url:
    url: https://download.argon40.com/argon1.sh
    dest: /tmp/argon40.sh

- name: Run script to install software
  ansible.builtin.command:
    cmd: bash /tmp/argon40.sh