---
- name: Check if the uninstall script is present
  ansible.builtin.stat:
    path: /etc/argon/argon-uninstall.sh
  register: uninstall_file

- name: Run uninstall script if it exists
  ansible.builtin.command:
    cmd: /etc/argon/argon-uninstall.sh
    stdin: "Y"
  register: script_result
  changed_when: script_result.rc == 0
  when: uninstall_file.stat.exists

- name: Download script
  ansible.builtin.get_url:
    url: https://download.argon40.com/argon1.sh
    dest: /tmp/argon40.sh
    mode: "0700" # U:RWX, G:N, O:N

- name: Run script to install software
  ansible.builtin.command:
    cmd: bash /tmp/argon40.sh
  register: script_result
  changed_when: script_result.rc == 0
