---
- name: Set defaults for variables
  ansible.builtin.set_fact:
    allow_ssh_keys: "{{ ssh_vars.auth.allow_keys | default(True) }}"
    allow_passwords: "{{ ssh_vars.auth.allow_passwords | default(False) }}"

- name: Enable SSH access via keys
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: PubkeyAuthentication
    line: PubkeyAuthentication yes
    owner: root
    group: root
    mode: "0644" # U:RW, G:R, O:R
    state: present
  when: allow_ssh_keys

- name: Disable SSH access via password
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: PasswordAuthentication
    line: PasswordAuthentication no
    owner: root
    group: root
    mode: "0644" # U:RW, G:R, O:R
    state: present
  when: not allow_passwords
