---
- name: Enable SSH access via keys
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: PubkeyAuthentication
    line: PubkeyAuthentication yes
    owner: root
    group: root
    mode: "0644" # U:RW, G:R, O:R
    state: present
  when: ssh_vars.auth.allow_keys

- name: Disable SSH access via password
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: PasswordAuthentication
    line: PasswordAuthentication no
    owner: root
    group: root
    mode: "0644" # U:RW, G:R, O:R
    state: present
