---
- name: Add public key to authorized_keys for current user
  vars:
    key: {{ lookup('file', pub_key.path) }}
  ansible.builtin.lineinfile:
    path: ~/.ssh/authorized_keys
    search_string: {{ key }}
    line: {{ key }}
    owner: {{ ansible_user }}
    mode: '700' # U:RWX, G:N, O:N
    state: present