---
- name: Get the model of the Raspberry Pi
  ansible.builtin.slurp:
    src: /sys/firmware/devicetree/base/model
  register: slurped_model

- set_fact:
    model: "{{ slurped_model.content | ansible.builtin.b64decode }}"
