---
ansible_host: 192.168.1.125

agent:
  labels:
    - starsystem.dev/games=true # Games will only run on nodes with this label
  taints:
    - starsystem.dev/games=true:PreferNoSchedule # Reserves a game node's resources unless the cluster doesn't have enough for other pods
