---
ansible_host: 192.168.1.121

drives:
  - mountpoint: /mnt/cluster/nfs
    device: /dev/sda1
    fs: ext4
  - mountpoint: /mnt/cluster/databases
    device: /dev/sdb1
    fs: ext4

server:
  labels:
    - class.node.cluster.starsystem.dev=database # Database Pods will use this label to identify which node to be scheduled on
  # Prevents Pods not related to database storage from being scheduled to, or executed on, this node
  # Should the compute resources be needed (e.g. other nodes go offline), then K8s is allowed to use this node
  taints:
    - taint.node.cluster.starsystem.dev=database:PreferNoSchedule
