---
ansible_host: 192.168.1.121

drives:
  - mountpoint: /mnt/cluster/nfs
    device: /dev/sda1
    fs: ext4
  - mountpoint: /mnt/cluster/databases
    device: /dev/sdb1
    fs: ext4

server:
  labels:
    - affinity.node.cluster.starsystem.dev=database # Databases like PostgreSQL & MySQL can use this node's storage & compute
    - affinity.node.cluster.starsystem.dev=nfs # Allows an NFS server to run on the node for remote storage for other pods
    - affinity.node.cluster.starsystem.dev=prometheus # Allows a Prometheus replica to run on this node and use its storage