---
ansible_host: 192.168.1.122

server:
  labels:
    - class.node.cluster.starsystem.dev=hypervisor # Makes K8s aware that this node is a hypervisor, currently has no affect

ssh:
  allow_root_login: true