---
ansible_host: 192.168.1.126

agent:
  labels:
    - starsystem.dev/minio=true # Indicates that this node can run a MinIO storage server
  taints:
    - starsystem.dev/nas=true:PreferNoSchedule # Like Clover's taint, this helps keep resources reserved for a peak in usage
