---
ansible_host: 192.168.1.126

agent:
  labels:
    - affinity.node.cluster.starsystem.dev=minio # Indicates that this node can run a MinIO storage server
  taints:
    - taint.node.cluster.starsystem.dev=nas:PreferNoSchedule # Like Clover's taint, this helps keep resources reserved for a peak in usage
