---
ansible_host: 192.168.1.126

agent:
  labels:
    - class.node.cluster.starsystem.dev=nas
  taints:
    - taint.node.cluster.starsystem.dev=nas:PreferNoSchedule
    - taint.node.cluster.starsystem.dev=nas:PreferNoExecute