---
ansible_host: 192.168.1.120

server:
  labels:
    - starsystem.dev/prometheus=true # Allows a Prometheus replica to run on this node and use its storage
    - starsystem.dev/rtc=true # Has a dedicated RTC for running an NTP server

raspberrypi:
  overclocking:
    enabled: true
    cpu_freq: 3000 # in MHz
    gpu_freq: 1000 # in MHz