---
- name: Copy kubeconfig to local machine
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: {{ local_copy.local_path }}
    flat: true # Otherwise, would be saved as {{ local_path }}/{{ remote_hostname }}/etc/rancher/k3s/k3s.yaml
  run_once: true # All kubeconfigs will be the same across all servers

- name: Generate updated server IP line
  ansible.builtin.set_fact:
    kubeconfig_remote_server: >- # > produces a single line, whereas | preserves newlines, - removes the newline at the end
      server: https://{{ local_copy.remote_ip }}:6443
  run_once: true

- name: Update server IP in kubeconfig
  ansible.builtin.lineinfile:
    search_string: "server: https://127.0.0.1:6443"
    line: {{ kubeconfig_remote_server | indent(4, True) }} # Adds 4 leading whitespaces to the line
    path: {{ local_copy.local_path }}
    state: present
  run_once: true